### ISSUE TITLE
Use `homepage` for npm links

### ISSUE THREAD

**Issue by avaly** [BrainMaestro/packagehub#3]
The links for node dependencies use the `repository_url` field from the libraries.io response. However most npm packages have that field with the following format: `git+URL.git`. The links should use the `homepage` field, at least for npm packages.

Example: https://libraries.io/api/npm/rollup

**Comment by BrainMaestro** [comment]
Hey that's a good shout. I'll take a look at that. Thanks

**Comment by BrainMaestro** [comment]
@avaly. Check out v0.8.0. It should be fixed now. I'll close this, but if you encounter the issue again, feel free to reopen this.
