### ISSUE TITLE
No way to add Libraries.io API key in Firefox

### ISSUE THREAD

**Issue by matrixik** [BrainMaestro/packagehub#4]
Hello, thank you for useful add-on.

I would like to report that there is no way to set Libraries.io API key in Firefox.
I can't see/add add-on icon on toolbar, nor add-on page have any configuration options.

Version 0.8.0.
Firefox 54.0 (64-bit) (on Ubuntu)

**Comment by BrainMaestro** [comment]
Hey @matrixik, I actually forgot to update the Firefox add-on. I'll do that right now, so you should be able to add an API key

**Comment by BrainMaestro** [comment]
This should be fixed with the new update. It was finally published after so long.

**Comment by matrixik** [comment]
Thank you for fix. I can confirm now I'm able to add API to the add-on.

One question: is add-on icon needed for anything else than setting API key? Because if not then I don't think it's needed at all, user could simply configure API key in add-on settings page, and forget about it (you could open it after add-on installed properly).
At last you could do this that way in Firefox, I don't know how it looks in Chrome.

**Comment by BrainMaestro** [comment]
Hey thanks for the suggestion. I was actually wondering if something like that was possible. I'll look into it and see if I can do it for both browsers.
