### ISSUE TITLE
Toml parser is not working in Firefox

### ISSUE THREAD

**Issue by matrixik** [BrainMaestro/packagehub#5]
In Firefox toml parser is not working (pip and cargo), it's working in Chrome.

In console I could see:
`TypeError: window.toml is undefined  parser.js:48:9`

Repos to test:
https://github.com/iamale/pipreq
https://github.com/joshtriplett/metadeps

Version 0.8.0.
Firefox 54.0 (64-bit) (on Ubuntu)

**Comment by BrainMaestro** [comment]
Hmm, with my version it seems to work. Can you try again after I update the plugin and let me know?

**Comment by matrixik** [comment]
OK, will do.

**Comment by BrainMaestro** [comment]
@matrixik, can you check and let me know if this works now?

**Comment by matrixik** [comment]
Hi, updated add-on and Firefox to 55.
Unfortunately still not working... Error in console:
With `Cargo.toml` file:
```uncaught exception: SyntaxError: Expected "#", "\n", "\r" or [ \t] but "n" found.  (unknown)```
With `Pipfile`
```uncaught exception: SyntaxError: Expected "#", "\n", "\r" or [ \t] but "u" found.  (unknown)```

This error is not showing on pages with `package.json`, and it's working with them.

**Comment by BrainMaestro** [comment]
Hey @matrixik. I've fixed the bug with the new version `1.0.3`, when you can update, let me know if it fixes it.

**Comment by matrixik** [comment]
Great, I can confirm it's working now with both files. Thank you.
